###########
# site.title

title:    'MalmoInvaders'
subtitle: 'CS 175: Project in AI (in Minecraft)'


#########################
# more settings
header-img: ghast.jpg
markdown: kramdown

exclude:
- README.md
- LICENSE.md
